BRPA-1110 InitiateCheckout event
vtex-apps/facebook-checkout-pixel pull request #1
Opened 2022-04-08 13:14 UTC by AToyama

#### What problem is this solving?
- Initial Commit
- Adding initiateCheckout event

#### Screenshots or example usage:

![Captura de Tela 2022-04-08 às 10 11 38](https://user-images.githubusercontent.com/11501135/162442506-be1ab5bd-4c16-40e5-b264-57549ef3e413.png)

#### Related to / Depends on

https://github.com/vtex-apps/facebook-capi
https://github.com/vtex-apps/facebook-fbe

2022-04-11 19:45 UTC, wagnerlduarte reviewed
Do you can split your PR startup next time. It's a better way, because it's easier review and understand what is boilerplate and what is new feature.

1. PR with startup template
2. PR with feature

2022-04-18 20:49 UTC, ConradoClark requested changes
Good job! I've just left a few suggestions and requested changes.

2022-04-18 20:49 UTC, ConradoClark commented on node/middlewares/notify.ts
> +    .map((e) => {
I'd use foreach here since you're not returning anything
```suggestion
    .forEach((e) => {
```

2022-04-18 20:49 UTC, ConradoClark commented on node/middlewares/notify.ts
> +        ...(e.eventObject as Object),
You can remove this cast to `Object` if you change `eventObject`'s type from `unknown` to `Record<string, unknown>`.

```suggestion
        ...e.eventObject,
```

2022-04-18 20:49 UTC, ConradoClark commented on node/typings/orderFormEvent.ts
> +  eventObject: unknown
This would allow you to use the spread syntax without casting it to `Object`:
```suggestion
  eventObject: Record<string, unknown>
```

2022-04-18 20:49 UTC, ConradoClark commented on react/OrderFormUpdateHandler.tsx
> +    'https://connect.facebook.net/en_US/fbevents.js'
I'd put this in a constants file

2022-04-18 20:49 UTC, ConradoClark commented on react/OrderFormUpdateHandler.tsx
> +    window.fbq = function () {
I think you can do this to avoid the lint warning:
```suggestion
    window.fbq = function fbq () {
```

2022-04-18 20:49 UTC, ConradoClark commented on react/eventHandlers/onEmailChanged.ts
> +
```suggestion
```

2022-04-28 11:22 UTC, wagnerlduarte commented on node/middlewares/notify.ts
> +    .map((e) => {
```suggestion
    .forEach((e) => {
```

2022-04-28 17:06 UTC, merged